// libs
import type { Metadata } from 'next'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import React, { ReactNode } from 'react'
import { ToastContainer } from 'react-toastify'

// components
import Layout from '../../components/modules/layouts/Layout'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: ReactNode
  params: Promise<{ locale: string }>
}

export default async function RootLayout({
  children,
  params,
}: Readonly<LayoutProps>) {
  const { locale } = await params
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ToastContainer
            position='bottom-right'
            autoClose={2000}
            hideProgressBar={false}
          />
          <Layout>{children}</Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
